### ISSUE TITLE
[BUG] Auto publish to npm not functional. 

### ISSUE THREAD

**Issue by sirdeggen** [bitcoin-sv/ts-sdk#62] opened 2024-05-10 20:53 UTC
## Bug Description

Title is enough. Just to track issue as known.

**Comment by ty-everett** [comment] 2024-05-10 23:21
I've been looking into this, and tried a few different strategies.

I got it to work once, by pushing a new version tag myself. Subsequently, it fails because it doesn't know what the latest version from NPM actually is, and has no way of committing the newly-published version back to the repo. Auto-increment and automating this has never worked, because GitHub Actions Runner doesn't have the ability to push to master.

I tried to add the bot as a repo admin, but it doesn't seem like this would be the right approach and I wasn't able to get that to work. One strategy could be to automatically create a pull request that bumps the version and then merge it, but that didn't seem to work either, and only maintainers can merge pull requests.

The code which Deggen has pushed is a good step in the right direction, and will work as long as people tag new versions in their `package.json` files within pull requests. i'll revert my PR-creating script version, and go back to that.

I'm not an expert on CI/CD automation, and I'm open to any suggestions from around the space.

**Comment by ty-everett** [comment] 2024-05-10 23:27
Reverted, and this approach has [worked](https://github.com/bitcoin-sv/ts-sdk/actions/runs/9039182627).

Now, the version on master equals the version on NPM. If a new version is put into `package.json` via some commit on master, it will successfully publish. Otherwise, it will throw an error and refuse to publish over an already-published version. I think that's the best we'll get for the time being, unless there's some other way.

**Comment by ty-everett** [comment] 2024-05-11 16:23
Apparently the build step was missing from the workflow, and since yesterday evening the latest version was being published without a `dist` folder. I pushed a fix and we've confirmed it's been resolved in `1.0.32`. I've also removed the automatic version bump, and will ask people to bump versions in `package.json` within their pull requests for now.

**Closed** 2024-05-30 18:45 UTC
Labels: bug
