### ISSUE TITLE
[BUG] Illegal Key Length

### ISSUE THREAD

**Issue by sirdeggen** [bitcoin-sv/ts-sdk#78] opened 2024-05-30 21:25 UTC
See this test fail randomly now and then
https://github.com/bitcoin-sv/ts-sdk/actions/runs/9309361953/job/25624631153?pr=76

Illegal key length in EncryptMessage. Probably a 1 in 256 problem or similiar?

Pinging @tonesnotes to please take a look if you have a moment.

**Comment by tonesnotes** [comment] 2024-05-31 05:49
Have investigated and determined the cause of the problem. You are correct, 1 in 256. When a key is created from an array with "leading zeros" its idea of its own length is reduced.
I've pinged Ty to get input on how he'd like to tweak the design to preserve the intended key length.

**Comment by tonesnotes** [comment] 2024-06-03 14:47
After consideration of the options, opted to zero extend keys in AES to the shortest standard length.

This better supports using the `BigNumber` class as a base class for keys.

**Comment by tonesnotes** [comment] 2024-06-03 14:48
PR created with fix and updated test.

**Comment by ty-everett** [comment] 2024-06-03 15:45
Code has been merged :)

**Closed by ty-everett** 2024-06-03 15:45 UTC
Labels: bug
